const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");
const prisma = new PrismaClient();

async function main() {
  const saltRounds = 10;

  // Seed admin user
  await prisma.user.create({
    data: {
      name: "Admin",
      email: "wlcmedia@gmail.com",
      password: await bcrypt.hash("123456", saltRounds),
      role: "admin",
    },
  });

  // Seed talents (dummy data from Aespa and IVE members with endorsement prices in Rupiah)
  const talents = [
    {
      name: "Karina",
      category: "Singer",
      userIG: "karinaxaespa",
      follIG: "12M",
      ERIG: 12.5,
      startfromIG: 225000000,
      userTikTok: "karinaaespaofficial",
      follTikTok: "5M",
      ERTikTok: 10.2,
      startfromTikTok: 150000000,
      path: "/images/talent/karina_photo.jpg",
      filename: "karina_photo.jpg",
    },
    {
      name: "Giselle",
      category: "K-Pop Idol",
      userIG: "giselleaespa",
      follIG: "11M",
      ERIG: 12.1,
      startfromIG: 225000000,
      userTikTok: "giselleofficial",
      follTikTok: "4.2M",
      ERTikTok: 9.8,
      startfromTikTok: 147000000,
      path: "/images/talent/giselle_photo.jpg",
      filename: "giselle_photo.jpg",
    },
    {
      name: "Winter",
      category: "Actor",
      userIG: "wintersnowflake",
      follIG: "11.5M",
      ERIG: 11.8,
      startfromIG: 210000000,
      userTikTok: "winterwonderland95",
      follTikTok: "4.5M",
      ERTikTok: 9.5,
      startfromTikTok: 142500000,
      path: "/images/talent/winter_photo.jpg",
      filename: "winter_photo.jpg",
    },
    {
      name: "NingNing",
      category: "Singer",
      userIG: "ningningaespa",
      follIG: "10.8M",
      ERIG: 11.5,
      startfromIG: 217500000,
      userTikTok: "ningningofficial",
      follTikTok: "4M",
      ERTikTok: 9.0,
      startfromTikTok: 135000000,
      path: "/images/talent/ningning_photo.jpg",
      filename: "ningning_photo.jpg",
    },
    {
      name: "Yujin",
      category: "Influencer",
      userIG: "yujinbaby",
      follIG: "8M",
      ERIG: 9.2,
      startfromIG: 180000000,
      userTikTok: "yujin1010",
      follTikTok: "3M",
      ERTikTok: 8.5,
      startfromTikTok: 120000000,
      path: "/images/talent/yujin_photo.jpg",
      filename: "yujin_photo.jpg",
    },
    {
      name: "Wonyoung",
      category: "Model",
      userIG: "wonyoungstar",
      follIG: "9M",
      ERIG: 10.1,
      startfromIG: 195000000,
      userTikTok: "wonyoung101",
      follTikTok: "3.5M",
      ERTikTok: 9.0,
      startfromTikTok: 127500000,
      path: "/images/talent/wonyoung_photo.jpg",
      filename: "wonyoung_photo.jpg",
    },
    {
      name: "Liz",
      category: "Model",
      userIG: "lizmodel",
      follIG: "7.2M",
      ERIG: 8.5,
      startfromIG: 168000000,
      userTikTok: "liz1010",
      follTikTok: "2.6M",
      ERTikTok: 7.0,
      startfromTikTok: 105000000,
      path: "/images/talent/liz_photo.jpg",
      filename: "liz_photo.jpg",
    },
    {
      name: "Leeseo",
      category: "Actor",
      userIG: "leeseoactor",
      follIG: "7M",
      ERIG: 8.4,
      startfromIG: 165000000,
      userTikTok: "leeseo101",
      follTikTok: "2.5M",
      ERTikTok: 7.0,
      startfromTikTok: 105000000,
      path: "/images/talent/leeseo_photo.jpg",
      filename: "leeseo_photo.jpg",
    },
    {
      name: "Gaeul",
      category: "All",
      userIG: "gaeuluniverse95",
      follIG: "7.5M",
      ERIG: 8.8,
      startfromIG: 172500000,
      userTikTok: "gaeulstarlight95",
      follTikTok: "2.8M",
      ERTikTok: 7.5,
      startfromTikTok: 112500000,
      path: "/images/talent/gaeul_photo.jpg",
      filename: "gaeul_photo.jpg",
    },
    {
      name: "Hana",
      category: "K-pop Idol",
      userIG: "hanaofficial95",
      follIG: "15M",
      ERIG: 14.2,
      startfromIG: 300000000,
      userTikTok: "hanaofficial95",
      follTikTok: "6M",
      ERTikTok: 11.5,
      startfromTikTok: 180000000,
      path: "/images/talent/hana_photo.jpg",
      filename: "hana_photo.jpg",
    },
    {
      name: "Minju",
      category: "Model",
      userIG: "minjuxmodel95",
      follIG: "9.5M",
      ERIG: 10.8,
      startfromIG: 210000000,
      userTikTok: "minju101095",
      follTikTok: "3.8M",
      ERTikTok: 9.2,
      startfromTikTok: 130000000,
      path: "/images/talent/minju_photo.jpg",
      filename: "minju_photo.jpg",
    },
    {
      name: "Rei",
      category: "Singer",
      userIG: "reiofficial95",
      follIG: "8M",
      ERIG: 9.5,
      startfromIG: 190000000,
      userTikTok: "reiofficial95",
      follTikTok: "3.2M",
      ERTikTok: 8.5,
      startfromTikTok: 120000000,
      path: "/images/talent/rei_photo.jpg",
      filename: "rei_photo.jpg",
    },

    {
      name: "Jisoo",
      category: "K-pop Idol",
      userIG: "jisooofficial95",
      follIG: "12M",
      ERIG: 13.2,
      startfromIG: 240000000,
      userTikTok: "jisooofficial95",
      follTikTok: "4.5M",
      ERTikTok: 10.5,
      startfromTikTok: 150000000,
      path: "/images/talent/jisoo_photo.jpg",
      filename: "jisoo_photo.jpg",
    },
    {
      name: "Chaeyoung",
      category: "K-pop Idol",
      userIG: "chaeyoungofficial95",
      follIG: "10M",
      ERIG: 11.8,
      startfromIG: 220000000,
      userTikTok: "chaeyoungofficial95",
      follTikTok: "4M",
      ERTikTok: 10.0,
      startfromTikTok: 140000000,
      path: "/images/talent/chaeyoung_photo.jpg",
      filename: "chaeyoung_photo.jpg",
    },
    {
      name: "Yoon",
      category: "Model",
      userIG: "yoonmodel95",
      follIG: "8.5M",
      ERIG: 9.8,
      startfromIG: 200000000,
      userTikTok: "yoon101095",
      follTikTok: "3.9M",
      ERTikTok: 9.5,
      startfromTikTok: 135000000,
      path: "/images/talent/yoon_photo.jpg",
      filename: "yoon_photo.jpg",
    },
    {
      name: "Soojin",
      category: "K-pop Idol",
      userIG: "soojinofficial95",
      follIG: "11M",
      ERIG: 12.5,
      startfromIG: 230000000,
      userTikTok: "soojinofficial95",
      follTikTok: "4.2M",
      ERTikTok: 10.8,
      startfromTikTok: 145000000,
      path: "/images/talent/soojin_photo.jpg",
      filename: "soojin_photo.jpg",
    },
    {
      name: "Jiheon",
      category: "Rapper",
      userIG: "jiheonofficial95",
      follIG: "9M",
      ERIG: 10.2,
      startfromIG: 210000000,
      userTikTok: "jiheonofficial95",
      follTikTok: "3.6M",
      ERTikTok: 9.0,
      startfromTikTok: 125000000,
      path: "/images/talent/jiheon_photo.jpg",
      filename: "jiheon_photo.jpg",
    },
  ];

  // Insert talents into the database
  await prisma.talent.createMany({
    data: talents,
  });

  // Seed category and portfolio items
  const categoryPorto = await prisma.categoryPorto.create({
    data: {
      name: "Music Videos",
    },
  });

  const portfolios = [
    {
      title: "Next Level",
      sow: "Music Video Production",
      talent: "Aespa",
      categoryId: categoryPorto.id,
      path: "/images/talent/next_level.mp4",
      filename: "next_level.mp4",
    },
    {
      title: "Bonajour",
      sow: "Brand Ambassador Bonajour",
      talent: "Rei",
      categoryId: categoryPorto.id,
      path: "/images/talent/porto1.jpeg",
      filename: "porto1.jpeg",
    },
    {
      title: "Black Mamba",
      sow: "Music Video Production",
      talent: "Aespa",
      categoryId: categoryPorto.id,
      path: "/images/talent/black_mamba.mp4",
      filename: "black_mamba.mp4",
    },
    {
      title: "CLIO",
      sow: "Brand Ambassador CLIO",
      talent: "Yujin",
      categoryId: categoryPorto.id,
      path: "/images/talent/porto2.jpeg",
      filename: "porto2.jpeg",
    },
    {
      title: "Girls",
      sow: "Music Video Production",
      talent: "Aespa",
      categoryId: categoryPorto.id,
      path: "/images/talent/girls.mp4",
      filename: "girls.mp4",
    },
    {
      title: "Chanel",
      sow: "Brand Ambassador Chanel",
      talent: "Aespa",
      categoryId: categoryPorto.id,
      path: "/images/talent/porto3.jpeg",
      filename: "porto3.jpeg",
    },
    {
      title: "Dreams Come True",
      sow: "Music Video Production",
      talent: "Aespa",
      categoryId: categoryPorto.id,
      path: "/images/talent/dreams_come_true.mp4",
      filename: "dreams_come_true.mp4",
    },
    {
      title: "Chopard",
      sow: "Brand Ambassador Chopard",
      talent: "Rei",
      categoryId: categoryPorto.id,
      path: "/images/talent/porto4.jpeg",
      filename: "porto4.jpeg",
    },
    {
      title: "Eleven",
      sow: "Music Video Production",
      talent: "IVE",
      categoryId: categoryPorto.id,
      path: "/images/talent/eleven.mp4",
      filename: "eleven.mp4",
    },
    {
      title: "Love Dive",
      sow: "Music Video Production",
      talent: "IVE",
      categoryId: categoryPorto.id,
      path: "/images/talent/love_dive.mp4",
      filename: "love_dive.mp4",
    },
    {
      title: "After Like",
      sow: "Music Video Production",
      talent: "IVE",
      categoryId: categoryPorto.id,
      path: "/images/talent/after_like.mp4",
      filename: "after_like.mp4",
    },
    {
      title: "I AM",
      sow: "Music Video Production",
      talent: "IVE",
      categoryId: categoryPorto.id,
      path: "/images/talent/i_am.mp4",
      filename: "i_am.mp4",
    },
  ];

  // Insert portfolios into the database
  await prisma.porto.createMany({
    data: portfolios,
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
